Spring:
  application:
    name: hello-spring-cloud-config
  cloud:
    config:
      label: master
      server:
        git:
#如果此处是gitlab ，git.uri 需要在结尾加上 .git，GitHub 则不用
#格式         http://ip:port/{label}/{application}-{profile}.yml
          uri: https://github.com/jianwei/spring-cloud-config
          search-paths:
          username:
          password:



server:
  port: 8888


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/




